import { IP_TYPE } from './bgpConst';

// 默认值
export const DEFAULT_VALUES = {
    DEFAULT_RPKI_PORT: '1280',
    DEFAULT_RPKI_ASN: '65535',
    DEFAULT_RPKI_IPV4: '1.1.1.1',
    DEFAULT_RPKI_IPV6: '2001:db8::1',
    DEFAULT_RPKI_MASKV4: '24',
    DEFAULT_RPKI_MASKV6: '128',
    DEFAULT_RPKI_MAX_LENGTHV4: '32',
    DEFAULT_RPKI_MAX_LENGTHV6: '128',
    DEFAULT_RPKI_IP_TYPE: IP_TYPE.IPV4
};
