// BGP default port number
const BGP_DEFAULT_PORT = 179;

const BGP_HEAD_LEN = 19; // 含16字节marker + 3字节固定头部

const BGP_MAX_PKT_SIZE = 4096;

// BGP version number
const BGP_VERSION = 4;

// BGP marker length (16 bytes of 0xff)
const BGP_MARKER_LEN = 16;

const BGP_RD_LEN = 8;

const IP_HOST_BYTE_LEN = 4;
const IPV6_HOST_BYTE_LEN = 16;

const IP_HOST_LEN = 32;
const IPV6_HOST_LEN = 128;

const BGP_PEER_STATE = {
    IDLE: 0,
    CONNECT: 1,
    ACTIVE: 2,
    OPEN_SENT: 3,
    OPEN_CONFIRM: 4,
    ESTABLISHED: 5,
    NO_NEG: 6
};

const BGP_PEER_STATE_NAME = {
    [BGP_PEER_STATE.IDLE]: 'Idle',
    [BGP_PEER_STATE.CONNECT]: 'Connect',
    [BGP_PEER_STATE.ACTIVE]: 'Active',
    [BGP_PEER_STATE.OPEN_SENT]: 'OpenSent',
    [BGP_PEER_STATE.OPEN_CONFIRM]: 'OpenConfirm',
    [BGP_PEER_STATE.ESTABLISHED]: 'Established',
    [BGP_PEER_STATE.NO_NEG]: 'No Neg'
};

const BGP_PACKET_TYPE = {
    OPEN: 1,
    UPDATE: 2,
    NOTIFICATION: 3,
    KEEPALIVE: 4,
    ROUTE_REFRESH: 5
};

// 协议规定的BGP open capability code
const BGP_OPEN_CAP_CODE = {
    MULTIPROTOCOL_EXTENSIONS: 0x01,
    ROUTE_REFRESH: 0x02,
    EXTENDED_NEXT_HOP_ENCODING: 0x05,
    FOUR_OCTET_AS: 0x41,
    ADD_PATH: 0x45,
    BGP_ROLE: 0x09
};

const IP_TYPE = {
    IPV4: 1,
    IPV6: 2
};

// 渲染进程传入的地址组类型
const BGP_ADDR_FAMILY = {
    IPV4_UNC: 1,
    IPV6_UNC: 2,
    L2VPN_EVPN: 3,
    VPNV4: 4,
    VPNV6: 5,
    IPV4_MVPN: 6,
    IPV6_MVPN: 7
};

// 协议规定的afi
const BGP_AFI_TYPE = {
    AFI_IPV4: 1,
    AFI_IPV6: 2,
    AFI_L2VPN: 25
};

// 协议规定的safi
const BGP_SAFI_TYPE = {
    SAFI_UNICAST: 1,
    SAFI_MVPN: 5,
    SAFI_EVPN: 70,
    SAFI_VPN: 128
};

// 协议规定的role
const BGP_ROLE_TYPE = {
    ROLE_PROVIDER: 0,
    ROLE_RS: 1,
    ROLE_RS_CLIENT: 2,
    ROLE_CUSTOMER: 3,
    ROLE_PEER: 4,
    ROLE_INVALID: 255
};

const BGP_ADD_PATH_TYPE = {
    SEND_ONLY: 1,
    RECEIVE_ONLY: 2,
    SEND_RECEIVE: 3
};

// 定义能力标志位掩码
const BGP_CAP_FLAGS = {
    MULTIPROTOCOL_EXTENSIONS: 0x00000001, // 1 << 0
    ROUTE_REFRESH: 0x00000002, // 1 << 1
    FOUR_OCTET_AS: 0x00000004, // 1 << 2
    BGP_ROLE: 0x00000008, // 1 << 3
    EXTENDED_NEXT_HOP_ENCODING: 0x00000010, // 1 << 4
    ADD_PATH: 0x00000020 // 1 << 5
};

// 定义能力标志位掩码
const BGP_MULTIPROTOCOL_EXTENSIONS_FLAGS = {
    IPV4_UNC: 0x00000001, // 1 << 0
    IPV6_UNC: 0x00000002, // 1 << 1
    IPV4_MVPN: 0x00000004, // 1 << 2
    IPV6_MVPN: 0x00000008 // 1 << 3
};

// BGP Path Attribute Types
const BGP_PATH_ATTR = {
    ORIGIN: 0x01,
    AS_PATH: 0x02,
    NEXT_HOP: 0x03,
    MED: 0x04,
    LOCAL_PREF: 0x05,
    ATOMIC_AGGREGATE: 0x06,
    AGGREGATOR: 0x07,
    COMMUNITY: 0x08,
    ORIGINATOR_ID: 0x09,
    CLUSTER_LIST: 0x0a,
    MP_REACH_NLRI: 0x0e,
    MP_UNREACH_NLRI: 0x0f,
    EXTENDED_COMMUNITIES: 0x10,
    AS4_PATH: 0x11,
    AS4_AGGREGATOR: 0x12,
    PMSI_TUNNEL: 0x16, // 22
    PATH_OTC: 0x23
};

const EXT_COMMUNITY_TYPE = {
    AS2: 0x0,
    IP: 0x1,
    AS4: 0x2
};

const EXT_COMMUNITY_SUB_TYPE = {
    RT: 0x2,
    SOO: 0x3
};

const RD_TYPE = {
    AS2: 0x0,
    IP: 0x1,
    AS4: 0x2
};

// BGP Path Attribute Flags
const BGP_PATH_ATTR_FLAGS = {
    OPTIONAL: 0x80,
    TRANSITIVE: 0x40,
    PARTIAL: 0x20,
    EXTENDED_LENGTH: 0x10
};

const BGP_OPEN_OPT_TYPE = {
    OPT_TYPE: 0x02
};

const BGP_ORIGIN_TYPE = {
    IGP: 0,
    EGP: 1,
    INCOMPLETE: 2
};

const BGP_AS_PATH_TYPE = {
    AS_SET: 1,
    AS_SEQUENCE: 2,
    AS_CONFED_SEQUENCE: 3,
    AS_CONFED_SET: 4
};

const BGP_ERROR_CODE = {
    MESSAGE_HEADER_ERROR: 1,
    OPEN_MESSAGE_ERROR: 2,
    UPDATE_MESSAGE_ERROR: 3,
    HOLD_TIMER_EXPIRED: 4,
    FSM_ERROR: 5,
    CONNECTION_REJECTED: 6
};

const BGP_ERROR_MESSAGE_HEADER_SUBCODE = {
    CONNECTION_NOT_SYNCHRONIZED: 1,
    BAD_MESSAGE_LENGTH: 2,
    BAD_MESSAGE_TYPE: 3
};

const BGP_ERROR_OPEN_MESSAGE_SUBCODE = {
    UNSUPPORTED_VERSION_NUMBER: 1,
    BAD_PEER_AS: 2,
    BAD_BGP_IDENTIFIER: 3,
    UNSUPPORTED_OPTIONAL_PARAMETER: 4,
    AUTHENTICATION_FAILURE: 5,
    UNACCEPTABLE_HOLD_TIME: 6,
    UNSUPPORTED_CAPABILITY: 7,
    ROLE_MISMATCH: 11
};

const BGP_ERROR_UPDATE_MESSAGE_SUBCODE = {
    ATTR_LIST_ERR: 1,
    UNKNOWN_ATTR: 2,
    ATTR_MISSING: 3,
    ATTR_FLAGS_ERROR: 4,
    ATTR_LENGTH_ERROR: 5,
    INVALID_ORIGIN_ATTR: 6,
    ATTR_ASLOOP: 7,
    INVALID_NEXT_HOP_ATTR: 8,
    OPTIONAL_ATTR_ERROR: 9,
    INVALID_NETWORK: 10,
    MALFORMED_AS_PATH: 11
};

const BGP_ERROR_CONNECTION_REJECTED_SUBCODE = {
    MAX_PREFIXES: 1,
    ADMIN_SHUTDOWN: 2,
    PEER_DE_CONFIGURED: 3,
    ADMIN_RESET: 4,
    CONNECTION_REJECTED: 5,
    CONNECTION_COLLISION_RESOLUTION: 6,
    OTHER_CONFIGURATION_CHANGE: 7,
    OUT_OF_RESOURCES: 8
};

const BGP_PEER_TYPE = {
    PEER_TYPE_INVALID: 0,
    PEER_TYPE_IBGP: 1,
    PEER_TYPE_EBGP: 2
};

// 事件类型
const BGP_EVT_TYPES = {
    BGP_PEER_CHANGE: 1
};

// 请求-响应类型
const BGP_REQ_TYPES = {
    START_BGP: 1,
    STOP_BGP: 2,
    CONFIG_IPV4_PEER: 3,
    CONFIG_IPV6_PEER: 4,
    DELETE_PEER: 5,
    GENERATE_IPV4_ROUTES: 6,
    GENERATE_IPV6_ROUTES: 7,
    DELETE_IPV4_ROUTES: 8,
    DELETE_IPV6_ROUTES: 9,
    GET_PEER_INFO: 10,
    GET_ROUTES: 11,
    GENERATE_IPV4_MVPN_ROUTES: 12,
    DELETE_IPV4_MVPN_ROUTES: 13,
    // Configuration
    SAVE_IPV4_MVPN_ROUTE_CONFIG: 30,
    LOAD_IPV4_MVPN_ROUTE_CONFIG: 31
};

const BGP_MVPN_ROUTE_TYPE = {
    INTRA_AS_I_PMSI_AD: 1,
    INTER_AS_I_PMSI_AD: 2,
    S_PMSI_AD: 3,
    LEAF_AD: 4,
    SOURCE_ACTIVE_AD: 5,
    SHARED_TREE_JOIN: 6,
    SOURCE_TREE_JOIN: 7
};

module.exports = {
    BGP_DEFAULT_PORT,
    BGP_HEAD_LEN,
    BGP_MAX_PKT_SIZE,
    BGP_VERSION,
    IP_HOST_BYTE_LEN,
    IPV6_HOST_BYTE_LEN,
    IP_HOST_LEN,
    IPV6_HOST_LEN,
    BGP_MARKER_LEN,
    BGP_PEER_STATE,
    BGP_PACKET_TYPE,
    BGP_OPEN_CAP_CODE,
    BGP_ADDR_FAMILY,
    BGP_AFI_TYPE,
    BGP_SAFI_TYPE,
    BGP_ROLE_TYPE,
    BGP_PATH_ATTR,
    BGP_PATH_ATTR_FLAGS,
    BGP_OPEN_OPT_TYPE,
    BGP_ORIGIN_TYPE,
    BGP_AS_PATH_TYPE,
    BGP_ERROR_CODE,
    BGP_ERROR_MESSAGE_HEADER_SUBCODE,
    BGP_ERROR_OPEN_MESSAGE_SUBCODE,
    BGP_ERROR_UPDATE_MESSAGE_SUBCODE,
    BGP_ERROR_CONNECTION_REJECTED_SUBCODE,
    BGP_PEER_STATE_NAME,
    IP_TYPE,
    BGP_CAP_FLAGS,
    BGP_MULTIPROTOCOL_EXTENSIONS_FLAGS,
    BGP_RD_LEN,
    BGP_PEER_TYPE,
    BGP_EVT_TYPES,
    BGP_REQ_TYPES,
    BGP_MVPN_ROUTE_TYPE,
    EXT_COMMUNITY_SUB_TYPE,
    EXT_COMMUNITY_TYPE,
    RD_TYPE,
    BGP_ADD_PATH_TYPE
};
