const BMP_HEADER_LENGTH = 6;

const BMP_INITIATION_TLV_TYPE = {
    SYS_NAME: 1,
    SYS_DESC: 2
};

// BMP message types (RFC 7854)
const BMP_MSG_TYPE = {
    ROUTE_MONITORING: 0,
    STATISTICS_REPORT: 1,
    PEER_DOWN_NOTIFICATION: 2,
    PEER_UP_NOTIFICATION: 3,
    INITIATION: 4,
    TERMINATION: 5,
    ROUTE_MIRRORING: 6
};

const BMP_MSG_TYPE_NAME = {
    [BMP_MSG_TYPE.ROUTE_MONITORING]: 'ROUTE_MONITORING',
    [BMP_MSG_TYPE.STATISTICS_REPORT]: 'STATISTICS_REPORT',
    [BMP_MSG_TYPE.PEER_DOWN_NOTIFICATION]: 'PEER_DOWN_NOTIFICATION',
    [BMP_MSG_TYPE.PEER_UP_NOTIFICATION]: 'PEER_UP_NOTIFICATION',
    [BMP_MSG_TYPE.INITIATION]: 'INITIATION',
    [BMP_MSG_TYPE.TERMINATION]: 'TERMINATION',
    [BMP_MSG_TYPE.ROUTE_MIRRORING]: 'ROUTE_MIRRORING'
};

// BMP peer types
const BMP_PEER_TYPE = {
    GLOBAL: 0,
    L3VPN: 1,
    LOCAL: 2,
    LOCAL_L3VPN: 3
};

// BMP peer flags
const BMP_PEER_FLAGS = {
    IPV6: 0x80,
    POST_POLICY: 0x40,
    AS_PATH: 0x20,
    ADJ_RIB_OUT: 0x10
};

module.exports = {
    BMP_HEADER_LENGTH,
    BMP_MSG_TYPE,
    BMP_PEER_TYPE,
    BMP_PEER_FLAGS,
    BMP_MSG_TYPE_NAME,
    BMP_INITIATION_TLV_TYPE
};
