// 事件类型
const BMP_EVT_TYPES = {
    ROUTE_MONITORING: 1,
    STATISTICS_REPORT: 2,
    PEER_DOWN_NOTIFICATION: 3,
    PEER_UP_NOTIFICATION: 4,
    INITIATION: 5,
    TERMINATION: 6,
    ROUTE_MIRRORING: 7
};

module.exports = { BMP_EVT_TYPES };
