// BMP operations
const BMP_OPERATIONS = {
    START_SERVER: 1,
    STOP_SERVER: 2,
    PEER_CONNECTED: 3,
    PEER_DISCONNECTED: 4,
    ROUTE_ANNOUNCED: 5,
    ROUTE_WITHDRAWN: 6,
    SERVER_LOG: 7,
    INITIATION_RECEIVED: 8
};

module.exports = { BMP_OPERATIONS };
