// 事件类型
const FTP_EVT_TYPES = {
    CLIENT_CONNECTION: 1,
    AUTHENTICATION: 2,
    FILE_TRANSFER_START: 3,
    FILE_TRANSFER_COMPLETE: 4,
    FILE_TRANSFER_ERROR: 5,
    DIRECTORY_LISTING: 6,
    COMMAND_EXECUTED: 7
};

// FTP请求-响应类型
const FTP_REQ_TYPES = {
    START_FTP: 1,
    STOP_FTP: 2
};

const DEFAULT_FTP_SETTINGS = {
    maxFtpUser: 10
};

module.exports = {
    FTP_EVT_TYPES,
    FTP_REQ_TYPES,
    DEFAULT_FTP_SETTINGS
};
