const RPKI_HEADER_LENGTH = 8;

// RPKI message types
const RPKI_MSG_TYPE = {
    PDU: 0,
    ERROR: 1,
    RESET_QUERY: 2,
    CACHE_RESPONSE: 3,
    IPV4_PREFIX: 4,
    IPV6_PREFIX: 6,
    END_OF_DATA: 7,
    CACHE_RESET: 8,
    ROUTER_KEY: 9,
    ERROR_REPORT: 10
};

const RPKI_MSG_TYPE_NAME = {
    [RPKI_MSG_TYPE.PDU]: 'PDU',
    [RPKI_MSG_TYPE.ERROR]: 'ERROR',
    [RPKI_MSG_TYPE.RESET_QUERY]: 'RESET_QUERY',
    [RPKI_MSG_TYPE.CACHE_RESPONSE]: 'CACHE_RESPONSE',
    [RPKI_MSG_TYPE.IPV4_PREFIX]: 'IPV4_PREFIX',
    [RPKI_MSG_TYPE.IPV6_PREFIX]: 'IPV6_PREFIX',
    [RPKI_MSG_TYPE.END_OF_DATA]: 'END_OF_DATA',
    [RPKI_MSG_TYPE.CACHE_RESET]: 'CACHE_RESET',
    [RPKI_MSG_TYPE.ROUTER_KEY]: 'ROUTER_KEY',
    [RPKI_MSG_TYPE.ERROR_REPORT]: 'ERROR_REPORT'
};

// RPKI Protocol Version
const RPKI_PROTOCOL_VERSION = {
    V0: 0,
    V1: 1,
    V2: 2
};

// RPKI Error Codes
const RPKI_ERROR_CODE = {
    CORRUPT_DATA: 0,
    INTERNAL_ERROR: 1,
    NO_DATA_AVAILABLE: 2,
    INVALID_REQUEST: 3,
    UNSUPPORTED_PROTOCOL_VERSION: 4,
    UNSUPPORTED_PDU_TYPE: 5,
    WITHDRAWAL_UNKNOWN: 6,
    DUPLICATE_ANNOUNCEMENT: 7
};

// RPKI PDU Flags
const RPKI_FLAGS = {
    ANNOUNCEMENT: 0,
    WITHDRAWAL: 1
};

// RPKI ROA Status
const RPKI_ROA_STATUS = {
    ACTIVE: 'active',
    PENDING: 'pending'
};

// Default RPKI Port
const RPKI_DEFAULT_PORT = 8282;

module.exports = {
    RPKI_HEADER_LENGTH,
    RPKI_MSG_TYPE,
    RPKI_MSG_TYPE_NAME,
    RPKI_PROTOCOL_VERSION,
    RPKI_ERROR_CODE,
    RPKI_FLAGS,
    RPKI_ROA_STATUS,
    RPKI_DEFAULT_PORT
};
