// SNMP事件类型
const SNMP_EVT_TYPES = {
    TRAP_EVT: 1
};

const SNMP_SUB_EVT_TYPES = {
    TRAP_RECEIVED: 1,
    AGENT_CONNECTION: 2,
    AGENT_DISCONNECTION: 3,
    TRAP_PROCESSED: 4,
    TRAP_ERROR: 5,
    SERVER_STATUS: 6
};

// SNMP请求-响应类型
const SNMP_REQ_TYPES = {
    START_SNMP: 1,
    STOP_SNMP: 2,
    GET_TRAP_LIST: 3,
    GET_TRAP_DETAIL: 4,
    CLEAR_TRAP_HISTORY: 5,
    UPDATE_CONFIG: 6
};

// SNMP版本
const SNMP_VERSION = {
    v1: 1,
    v2c: 2,
    v3: 3
};

// SNMP PDU类型
const SNMP_PDU_TYPE = {
    GET_REQUEST: 0xa0,
    GET_NEXT_REQUEST: 0xa1,
    GET_RESPONSE: 0xa2,
    SET_REQUEST: 0xa3,
    TRAP: 0xa4,
    GET_BULK_REQUEST: 0xa5,
    INFORM_REQUEST: 0xa6,
    SNMPV2_TRAP: 0xa7,
    REPORT: 0xa8
};

// SNMP安全级别（SNMPv3）
const SNMP_SECURITY_LEVEL = {
    NO_AUTH_NO_PRIV: 1,
    AUTH_NO_PRIV: 2,
    AUTH_PRIV: 3
};

// 默认设置
const DEFAULT_SNMP_SETTINGS = {
    maxTrapHistory: 1000,
    port: 162,
    timeout: 5000
};

const SNMP_BER_ASN1_TAG = {
    SEQUENCE: 0x30,
    INTEGER: 0x02,
    OCTET_STRING: 0x04,
    OBJECT_IDENTIFIER: 0x06,
    NULL: 0x05,
    IP_ADDRESS: 0x40,
    COUNTER32: 0x41,
    GAUGE32: 0x42,
    TIME_TICKS: 0x43,
    OPAQUE: 0x44,
    COUNTER64: 0x46
};

module.exports = {
    SNMP_EVT_TYPES,
    SNMP_REQ_TYPES,
    SNMP_VERSION,
    SNMP_PDU_TYPE,
    SNMP_SECURITY_LEVEL,
    DEFAULT_SNMP_SETTINGS,
    SNMP_SUB_EVT_TYPES,
    SNMP_BER_ASN1_TAG
};
